#!/bin/bash
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

name=$1
java -ea -cp bin:lib/antlr-4.4-complete.jar Main $1

